### ISSUE TITLE
Help debugging devise in anycable :(

### ISSUE THREAD

**Issue by hbhanoo** [anycable/anycable-rails#136]
### What did you do?
Load page

### What did you expect to happen?
User correctly identified by channel code

### What actually happened?
User was not identified.

---

Hi,
I know this must be an FAQ, but I think I've scoured all the docs I could find. I'm guessing I'm doing something silly, but I can't figure out what.

I've set up anycable on localhost, but the behavior I'm seeing seems to imply that devise is somehow not getting configured.

I have the initializer set up per the docs:

```
# Add Warden middleware to AnyCable stack to allow accessing
# Devise current user via `env["warden"].user`.
#
# See https://docs.anycable.io/#/v1/rails/authentication
AnyCable::Rails::Rack.middleware.use Warden::Manager do |config|
  Devise.warden_config = config
  STDERR.puts "anycable using warden we think? #{Devise.warden_config.inspect}"
end
```

which prints the following message:

`anycable using warden we think? {:default_scope=>:default, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>true}`

## Other info:

The 'set-cookie' received when loading the main rails page matches the cookie sent while trying to connect to action-cable (ie. I don't think it's a cookie issue).

In my ApplicationCable::Connection#connect class, 
```
    def connect
      puts "warden: #{env['warden']}"
```
gives
`warden: Warden::Proxy:70336246821020 @config={:default_scope=>:default, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>true}`

whereas when I run with `adapter: async` I get

`Warden::Proxy:70342128690420 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x00007ff39fb56ec8>}`

### Tell us about your environment

**Ruby version:** 2.6.6

**Rails version:** 6.0.3.1

**`anycable` gem version:** 1.0.1

**`anycable-rails` gem version:** 1.0.1

**`grpc` gem version:** 1.30.2

**Comment by hbhanoo** [comment]
ugh. I just had to submit this to figure it out. I was using 
```
env['warden'].user
```
in my code. I tried using
```
env['warden'].user(:user)
```
and I think that did it.

**Comment by denis-tchaikovsky** [comment]
I had similar issue, but in my case both `env['warden'].user` and `env['warden'].user(:user)` were returning `nil`. 

The app tech stack includes AnyCable and Stimulus Reflex. `session_store` is configured to be based on `cache_store` which in turn is based on Redis. 

Turned out the issue was caused by following: AnyCable and `session_store` were using separate Redis databases. After switching AnyCable to the use same Redis database as in `session_store`, the issue got resolved and 
`env['warden'].user(:user)` is returning the user object.

Just wanted to share the fix in case if someone would face similar issue.
