### ISSUE TITLE
ActionCable.server.broadcast equivalent

### ISSUE THREAD

**Issue by RailsCod3rFuture** [anycable/anycable-rails#150]
I'm a tad bit confused on finding the approach that I normally would use when broadcasting a channel -- look at the action below. How is this done with anycable?

def show
   ActionCable.server.broadcast("call_channel", call_params)
end

**Comment by KMarshland** [comment]
Did you find a solution to this?

**Comment by RailsCod3rFuture** [comment]
No. I don't know the scope of any-cable's hijacking capabilities....It works perfectly with hotwire/turbo.js....I just don't know if it overrides action cable's functionalities but allows you to use them???

**Comment by KMarshland** [comment]
Dang. Thanks for the rapid response; I'm currently trying to figure out why `AnyCable.broadcast 'mission_control', JSON({key: 'value'})` isn't getting to the browser.

**Comment by RailsCod3rFuture** [comment]
I will re-open for the sake of getting a real answer from the gem's maintainer.

**Comment by KMarshland** [comment]
Thanks RailsCod3rFuture. You're welcome to close again; I think the problem I'm experiencing is caused by something else.

For future debuggers, `AnyCable.broadcast` does indeed work as expected. If you're seeing errors like "Failed to parse pubsub message", you need to JSON serialize your message; `ActionCable.server.broadcast` will do that for you. The reason why my messages weren't getting to the browser was instead caused by the channel returning early because it couldn't find the devise user. There are other resources, including https://docs.anycable.io/#/v1/rails/authentication?id=devisewarden which will hopefully lead to a solution to that.
