### ISSUE TITLE
incompatible with dotenv

### ISSUE THREAD

**Issue by trc-ylin** [anycable/anycable-rails#23]
Hello,

Whenever I convert my anycable.yml into using dotenv, it breaks.

This configuration of anycable.yml **DOES** work.

> production:
>  rpc_host: 0.0.0.0:50051
>  redis_url: redis://redis:6379/0
>  redis_channel: __anycable__

however this configuration **DOES NOT** work.

> <%= ENV.fetch('RAILS_ENV') %>:
>   rpc_host: <%= ENV.fetch('RPC_HOST') %>
>   redis_url: <%= ENV.fetch('REDIS_FULL_URL') %>
>   redis_channel: __anycable__

here are the applicable environment variables (exact same values):
          - name: RAILS_ENV
            value: production
          - name: RPC_HOST
            value: 0.0.0.0:50051
          - name: REDIS_FULL_URL
            value: redis://redis:6379/0
          - name: REDIS_CHANNEL
            value: __anycable__

and the logs for the anycable service (using the default image from dockerhub):

Running websocket server on 0.0.0.0:8080 at /cable
2017/11/21 21:49:52 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.0.0.232:50051: getsockopt: connection refused"; Reconnecting to {"vcbe-ws:50051" <nil>}
2017/11/21 21:49:52 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.0.0.232:50051: getsockopt: connection refused"; Reconnecting to {"vcbe-ws:50051" <nil>}

If you're wondering what "vcbe-ws:50051" is, it's the name of a service that points to the grpc host, this whole thing is running on my minikube cluster at the moment. The exact replica is also running on our alpha kubernetes cluster. Dotenv works with all other configuration including cable.yml which looks like the following:

> <%= ENV.fetch('RAILS_ENV') %>:
>   :url: <%= ENV.fetch('REDIS_URL') %>
>   :port: <%= ENV.fetch('REDIS_PORT') %>
>   :db: 0
>   :adapter: redis
>   :namespace: cache
> 

Everything else on the environment stays exactly the same. The only thing that causes it to break is when I switch to have anycable.yml pull its values from environmental variables.

Thank you :)

**Comment by palkan** [comment]
Hi, @trc-ylin!

Do you mean that `vcbe-ws:50051` is wrong address or what? What is the expected behaviour?

> 2017/11/21 21:49:52 grpc: addrConn.resetTransport failed to create client transport: connection error: 

That could happen when RPC server is not ready to accept connections yet (it takes some time to load Rails app). 
Btw, you're running a rather old version of `anycable-go`. It's better to upgrade to the latest one (0.5.x for both `anycable-rails` and `anycable-go`).

Nevertheless, I don't think the problem with dotenv (it looks correct) and RPC service. Maybe, there is some env variable overlapping (see the list of `anycable-go` env variable here https://hub.docker.com/r/anycable/anycable-go/).

**Comment by trc-ylin** [comment]
Hello @palkan 
vcbe-ws:50051 is the gRPC service, I was only telling you in case you wanted to know. 
The expected behaviour is that it just works. If I replace the following with the actual values it works fine.
> <%= ENV.fetch('RAILS_ENV') %>:
> rpc_host: <%= ENV.fetch('RPC_HOST') %>
> redis_url: <%= ENV.fetch('REDIS_FULL_URL') %>

I've tried letting the rails + gRPC service load up first and then starting anycable, that doesn't work either. Regarding your last point, no there isn't any overlap, anycable-go is running in its own pod with its own set of environmental variables.

It breaks whenever anycable.yml pulls its values from environmental variables.

**Comment by palkan** [comment]
> It breaks whenever anycable.yml pulls its values from environmental variables.

What exactly breaks?

If it's possible try to compare the value of `Anycable.config` when specifying exact values and when using ENV.

It's not clear to me what goes wrong here.

**Comment by LaithAzer** [comment]
Hi @palkan 

I work with @trc-ylin and trying to resolve this issue.

To better show what we mean, here is en example showing what gets picked up by anycable and what doesn't.

Here is the yml file (to show what happens when we use hard-coded values vs ENV vars):

```
# anycable.yml
development:
  rpc_host: <%= ENV.fetch('RPC_HOST') %>
  redis_url: redis://db.local.pos:6379/0
  redis_channel: __anycable__
```

In the anycable bin file, I put a `puts config.inspect` statement, and this is what shows up when we run the server:

```
#<Anycable::Config:0x0000000002790188 @config_name="anycable", @rpc_host="<%= ENV.fetch('RPC_HOST') %>", @redis_url="redis://db.local.pos:6379/0", @redis_channel="__anycable__", @debug=false>
```

As you can see, the hard-coded values get picked up no problem, but anything using ENV vars gets parsed as a string for some reason.

Thanks a lot for looking into this!

**Comment by palkan** [comment]
Hi @LaithAzer!

Thanks! Now I see. AnyCable uses [anyway_config](https://github.com/palkan/anyway_config) which supports YAML ERB interpolation since version 1.0.0 and `erb` should be required manually (but Rails do that for you).

Which version of `anycable-rails` and `anyway_config` do you have?

**Comment by LaithAzer** [comment]
We use:

* `anycable-rails (0.4.7)`
* `anyway_config (0.5.1)`

But.. I just upgraded both and it works! 🙌 

Thank you so much!

**Comment by palkan** [comment]
@LaithAzer Make sure to upgrade anycable-go to 0.5.1 too

**Comment by trc-ylin** [comment]
will do.

Appreciate it :)
